spring.application.name=Evote

#Parametrage de l'acces à la base de données
spring.datasource.url=jdbc:mysql://localhost:3306/evote_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081

# Dialecte Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update


